controllers/CategoriesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Categories;
use app\models\CategoriesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;
use yii\data\Pagination;
use yii\data\Sort;
use yii\db\Query;
use yii\data\ActiveDataProvider;

/**
 * CategoriesController implements the CRUD actions for Categories model.
 */
class CategoriesController extends Controller
{
    public $widzet=false; 
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Categories models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategoriesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionPages(){
     $parent =  Yii::$app->request->get('pages');
    
    $query = new Query();
    $provider = new ActiveDataProvider([
    'query' => $query->from('in_page')->where(['page_id'=>$parent,'show'=>1]),
    'sort' => [
        // Set the default sort by name ASC and created_at DESC.
        'attributes' => [
           
            'created' => SORT_DESC
        ]
    ],
    'pagination' => [
        'pageSize' => 1,
    ],
]);
     $model = $provider->getModels();
     $pages = $provider->getPagination();
       $this->widzet=true;
       return  $this->render('pages',['pages'=>$pages,'model'=>$model,"widget"=>$this->widzet]);
    }
    
    public  function actionList(){
        
      $sort = new Sort([
        'attributes' => [
           
            'title' => [
                'asc' => ['title' => SORT_ASC, ],
                'desc' => ['title' => SORT_DESC],
                'default' => SORT_DESC,
                'label' => 'by Name',
            ],
            'created' => [
                'asc' => ['created' => SORT_ASC, ],
                'desc' => ['created' => SORT_DESC],
                'default' => SORT_DESC,
                'label' => 'by Date',
            ],
        ],
    ]);
      $query = new Query();
      if($tag = Yii::$app->request->get('tag')){
          $tag =$tag;
        //  $query->filterWhere(['LIKE' ,'meta_tags',strtr($tag,['%'=>'\%', '_'=>'\_', '\\'=>'\\\\']),'%', false]);
      }
      else{
           $tag="";
      }
      
    $provider = new ActiveDataProvider([
    'query' => $query->from('in_page')->Where(['show'=>1])->andWhere(['LIKE' ,'meta_tags','%'.strtr($tag,['%'=>'\%', '_'=>'\_', '\\'=>'\\\\']).'%', false])->orderBy($sort->orders),
    'sort' => [
        // Set the default sort by name ASC and created_at DESC.
        'attributes' => [
           
            'created' => SORT_DESC
        ]
    ],
    'pagination' => [
        'pageSize' => 3,
       
    ],
]);
   
     $model = $provider->getModels();
     $pages = $provider->getPagination();
     
     
       return  $this->render('pages',['pages'=>$pages,'model'=>$model,'sorter'=>$sort,"widget"=>$this->widzet]);
    }

    /**
     * Displays a single Categories model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Categories model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Categories();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->category_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Categories model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
          if (!\Yii::$app->user->can('adminCan')) {
            throw new ForbiddenHttpException('Access denied');
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->category_id]);
        } else {
            //  print_r($model->oldTag);
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Categories model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
          if (!\Yii::$app->user->can('adminCan')) {
            throw new ForbiddenHttpException('Access denied');
        }
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Categories model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Categories the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Categories::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/categories/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\SwitchInput;
use kartik\widgets\Select2;
/* @var $this yii\web\View */
/* @var $model app\models\Categories */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="categories-form ">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model); ?>
    <?php // $form->field($model, 'parent_id')->dropDownList($model->getCategoryList(), ['prompt' => 'Parent Category']); ?>
    <?= $form->field($model, 'parent_id')->widget(Select2::classname(), [
    'language' => 'en',
       
    'data' => $model->getCategoryList(),
    'options' => ['placeholder' => 'Parent Category ...'],
    'pluginOptions' => [
        'allowClear' => true,
         'size'=>'SMALL',
    ],
]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'about')->textarea(['rows' =>3,'class'=>'editor' ]) ?>

    <?php //= $form->field($model, 'url')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'meta')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'meta_tags')->textInput(['maxlength' => 255,'class'=>'tags']) ?>

   

    <?= $form->field($model, 'show')->widget(SwitchInput::classname(), []); ?>

   

   

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/categories/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CategoriesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="categories-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'category_id') ?>

    <?= $form->field($model, 'parent_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'about') ?>

    <?= $form->field($model, 'url') ?>

    <?php // echo $form->field($model, 'meta') ?>

    <?php // echo $form->field($model, 'meta_tags') ?>

    <?php // echo $form->field($model, 'pos') ?>

    <?php // echo $form->field($model, 'show') ?>

    <?php // echo $form->field($model, 'created') ?>

    <?php // echo $form->field($model, 'view') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/categories/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Categories */

$this->title = Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Category',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="categories-create col-md-7">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
       
    ]) ?>

</div>

views/categories/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\widgets\DatePicker;
/* @var $this yii\web\View */
/* @var $searchModel app\models\CategoriesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Categories');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="categories-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Categories',
]), ['create'], ['class' => 'btn btn-success']) ?>
         <?= Html::a(Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Page',
]), ['/page/create'], ['class' => 'btn btn-primary']) ?>
  <?= Html::a(Yii::t('app', 'Pages {modelClass}', [
    'modelClass' => 'List',
]), ['/page/index'], ['class' => 'btn btn-info']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
          
            'category_id',
            'parent_id',
            'title',
            'about',
            'url:url',
            // 'meta',
            // 'meta_tags',
            // 'pos',
             'show',
            // 'created',
              ['attribute'=>'created',
            'format' => ['date', 'php:d-M-Y'],
           // 'value' =>function($model){ return date('d-M-Y',strtotime($model->created));},
  
     'filter'=>DatePicker::widget([
    'name' => 'check_issue_date', 
    'value' => date('d-M-Y', strtotime('now')),
    'options' => ['placeholder' => 'Select date'],
    'pluginOptions' => [
        'format' => 'd-M-Y',
        'todayHighlight' => true
    ]
])
                ],
            // 'view',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/categories/pages.php
<?php
use yii\widgets\LinkPager;
use yii\widgets\Pjax;
use yii\widgets\LinkSorter;
use app\widzets\soc\SocialWidget;
use yii\helpers\Url;
use app\models\Page;
?>

<?php Pjax::begin(); ?>

<div class="col-md-10">
    <?php if(isset($sorter)){ echo LinkSorter::widget(['sort'=>$sorter]); }?> 
 <?php foreach ($model as $cat): ?>
   
     <div class="panel ">
               <div class="panel2 panel-heading "><?= $cat['title'] ?></div>
                <div class="panel-body">
                   <?=  $cat['topic'] ; ?>
                    
                </div>
               <?php if($widget != true): ?>
               <div><a class="btn btn-default btn-sm" data-pjax="0" href="<?=Url::to('/categories/'.$cat['page_id'])?>">Read more ..</a></div>
               <?php else: ?>
               <div><a class="btn btn-default btn-sm" data-pjax="0" href="<?=Url::to('/categories/list')?>">Back ..</a></div>

               <?php endif;?>
              
               <div class="panel-footer">
               <?= \Yii::$app->formatter->format($cat['created'], 'date') ?>
                    <em>Category: <?= Page::findCategory($cat['category_id']) ?></em>
               </div>
               <?php if($widget): ?>
                 <div><?= SocialWidget::widget(); ?></div>
               <?php endif;?>
                
     </div>
<?php endforeach; ?>

<?= LinkPager::widget(['pagination' => $pages]) ?>
</div>
<?php Pjax::end(); ?>

views/categories/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Categories */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Category',
]) . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->category_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="categories-update col-md-7">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/categories/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Categories */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="categories-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->category_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->category_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'category_id',
            'parent_id',
            'title',
            'about',
            'url:url',
            'meta',
            'meta_tags',
            'pos',
            'show',
            'created',
            'view',
        ],
    ]) ?>

</div>